/* autogenerated by Processing revision 1290 on 2023-02-28 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class terrain_generator extends PApplet {

int cols, rows;
int scl = 20;
int w = 2200;
int h = 1000;

float[][] terrain;
float flying = 0;

public void setup() {
    /* size commented out by preprocessor */;
  
    cols = w / scl;
    rows = h / scl;
    
    terrain = new float[cols][rows];
         
}

public void draw(){
  flying -= 0.01f;
  
   float ioff = flying;
    for(int i = 0; i < rows; i++){
        float joff = 0;
        for(int j = 0; j < cols; j++){
          terrain[j][i] = map(noise(joff,ioff), 0, 1, -100, 100);
          joff += 0.1f;
        } 
        ioff +=0.1f;
        }  
    background(0);
    stroke(255);
    noFill();
    
    translate(width/2, height/2);
    rotateX(PI/3);
    
    translate(-w/2, -h/2);

    for(int i = 0; i < rows -1 ; i++){
        beginShape(TRIANGLE_STRIP);
        for(int j = 0; j < cols; j++){
          vertex(j * scl, i * scl, terrain[j][i]);
          vertex(j * scl, (i+1) * scl, terrain[j][i+1]);

            //rect(i * scl, j * scl, scl, scl);
        }
        endShape();
    }
}


  public void settings() { size(1000, 800, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "terrain_generator" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
